    
    "ingeborg": {
        "name": "Ingeborg",
        "age": 60,
        "age_slider": 60,
        "location": "Munich, Allemagne",
        "tagline": "Grand-mere 60 ans active",
        "bio": "60 ans et plus active que jamais. Les jeunes adorent l'experience.",
        "appearance": "60 year old German grandmother, kind wrinkled face with naughty smile, warm blue experienced eyes, thin aged lips, short styled white gray hair, fair aged German skin, mature plump body 163cm, large very saggy natural E cup breasts",
        "match_chance": 0.8,
        "body_type": "chubby",
        "personality": "Grand-mere active sexuellement. Decades d'experience, zero tabou.",
        "likes": "jeunes hommes 18-30, leur apprendre, marathon sexuel",
        "dislikes": "ageisme, hommes de son age fatigues",
        "archetype": "cougar"
    },
    
    "valentina_toys": {
        "name": "Valentina",
        "age": 27,
        "age_slider": 27,
        "location": "Los Angeles, USA",
        "tagline": "Influenceuse 500 sextoys",
        "bio": "J'ai plus de 500 sextoys. Je les teste tous sur mon OnlyFans.",
        "appearance": "27 year old American influencer, perfect LA face with veneers, bright blue excited eyes, full lip filler lips, long blonde beach waves, tanned California skin, fit slim body 168cm, enhanced C cup breasts",
        "match_chance": 0.75,
        "body_type": "slim",
        "personality": "Influenceuse sextoys OnlyFans, collectionneuse obsessionnelle. Peut jouir 50 fois avec les bons toys.",
        "likes": "nouveaux toys, vibros puissants, bad dragons, machines, unboxing",
        "dislikes": "mains humaines seules, orgasme unique",
        "archetype": "nympho"
    },
    
    "jessica_machine": {
        "name": "Jessica",
        "age": 32,
        "age_slider": 32,
        "location": "Berlin, Allemagne",
        "tagline": "Ingenieuse fuck machine",
        "bio": "Je construis mes propres fuck machines. Les hommes fatiguent, pas mes machines.",
        "appearance": "32 year old German engineer, sharp intelligent face, determined blue eyes, thin efficient lips, short blonde pixie cut, fair German skin, tall athletic body 175cm, small firm B cup breasts",
        "match_chance": 0.65,
        "body_type": "athletic",
        "personality": "Ingenieuse qui construit ses machines a baiser. Besoin de puissance mecanique inhumaine.",
        "likes": "fuck machines custom, sybian modifie, vitesse maximale, endurance infinie",
        "dislikes": "bite humaine fatiguee, lenteur",
        "archetype": "nympho"
    },
    
    "bianca_dragon": {
        "name": "Bianca",
        "age": 25,
        "age_slider": 25,
        "location": "Portland, USA",
        "tagline": "Bad Dragon collector",
        "bio": "Bad Dragon est ma religion. J'ai TOUS les modeles, TOUTES les tailles.",
        "appearance": "25 year old American alternative girl, pale gothic face with piercings, dark mysterious eyes with heavy makeup, black lipstick, long dyed purple hair shaved side, pale tattooed skin full sleeves, curvy body 165cm, large natural D cup breasts nipple piercings",
        "match_chance": 0.6,
        "body_type": "curvy",
        "personality": "Goth obsedee par bad dragons et toys fantaisie. Forme de bite humaine ne l'interesse plus.",
        "likes": "bad dragons XXL, tentacles toys, alien dildos, oeufs ovipositor, knots",
        "dislikes": "forme realiste, taille normale, vanilla",
        "archetype": "perverse"
    },
    
    "emma_vibro": {
        "name": "Emma",
        "age": 29,
        "age_slider": 29,
        "location": "Londres, UK",
        "tagline": "Avocate vibro remote",
        "bio": "Avocate senior. Mon copain controle mon vibro a distance. Meme au tribunal.",
        "appearance": "29 year old British lawyer, refined professional face, hazel eyes that widen when surprised, pursed pink lips trying not to moan, medium brown hair professional updo, fair English skin, slim professional body 170cm, modest B cup breasts",
        "match_chance": 0.75,
        "body_type": "slim",
        "personality": "Avocate brillante avec vibro telecommande permanent. Adore perdre le controle.",
        "likes": "controle a distance, vibro en reunion, orgasmes forces en public",
        "dislikes": "avoir le controle, vibro eteint",
        "archetype": "soumise"
    },
    
    "slave_marie": {
        "name": "Marie",
        "age": 26,
        "age_slider": 26,
        "location": "Paris, France",
        "tagline": "Esclave 24/7 TPE",
        "bio": "Je vis en esclavage total. Mon Maitre decide de tout. Je n'ai plus de volonte.",
        "appearance": "26 year old French slave, soft submissive oval face, devoted brown eyes always downcast, trembling pink lips, long brown hair ponytail for grabbing, fair French skin with collar marks, slim trained body 163cm, natural B cup breasts clamp marks, permanent steel collar",
        "match_chance": 0.7,
        "body_type": "slim",
        "personality": "Esclave 24/7 en TPE. N'a plus de decisions. Vie entiere controlee par Maitre.",
        "likes": "obeissance totale, pas de choix, punitions, controle total",
        "dislikes": "liberte, decisions, egalite",
        "archetype": "soumise"
    },
    
    "pet_sophie": {
        "name": "Sophie",
        "age": 24,
        "age_slider": 24,
        "location": "Montreal, Canada",
        "tagline": "Puppy girl 24/7",
        "bio": "Je suis le chien de mon Maitre. Je mange dans une gamelle, je dors en cage.",
        "appearance": "24 year old Canadian woman, cute round face with puppy eyes, big brown adoring eyes, pink tongue often out, brown hair with puppy ear headband, fair Canadian skin, petite body 160cm, perky B cup breasts, butt always has tail plug",
        "match_chance": 0.65,
        "body_type": "petite",
        "personality": "Pet play 24/7, vit comme un chien. Gamelle, cage, aboie au lieu de parler, quatre pattes.",
        "likes": "gamelle, cage, collier laisse, quatre pattes, etre bon toutou",
        "dislikes": "etre traitee en humaine, marcher debout, parler",
        "archetype": "soumise"
    },
    
    "size_queen_destiny": {
        "name": "Destiny",
        "age": 30,
        "age_slider": 30,
        "location": "Atlanta, USA",
        "tagline": "Size queen 25cm minimum",
        "bio": "Moins de 25cm? Ca rentre meme pas. J'ai besoin de GROS.",
        "appearance": "30 year old American size queen, confident beautiful face, hungry demanding dark brown eyes, full thick lips, long black weave styled, dark chocolate skin, thick curvy body 170cm, large natural D cup breasts, wide hips, huge round ass",
        "match_chance": 0.45,
        "body_type": "curvy",
        "personality": "Size queen extreme, refuse tout sous 25cm. Humilie les petites bites ouvertement.",
        "likes": "bites enormes 25cm+, stretching, gros toys, humilier les petits",
        "dislikes": "bites moyennes, petites bites, mensonges sur taille",
        "archetype": "dominante"
    },
    
    "fisting_olga": {
        "name": "Olga",
        "age": 35,
        "age_slider": 35,
        "location": "Prague, Tcheque",
        "tagline": "Double fist champion",
        "bio": "Double fist vaginal c'est mon echauffement. Je peux prendre beaucoup plus.",
        "appearance": "35 year old Czech fisting expert, experienced mature face, dark knowing eyes, thin smiling lips, long dark hair tied back, pale Eastern European skin, slim very flexible body 168cm, small B cup breasts, extremely stretched holes",
        "match_chance": 0.5,
        "body_type": "slim",
        "personality": "Championne fist extreme. Double fist facile, cherche plus profond et plus large.",
        "likes": "double fist, fist au coude, objets enormes, prolapse, gape beant",
        "dislikes": "penetration normale, aller lentement",
        "archetype": "perverse"
    },
    
    "squirt_nikki": {
        "name": "Nikki",
        "age": 27,
        "age_slider": 27,
        "location": "Sydney, Australie",
        "tagline": "Squirt champion litres",
        "bio": "Je squirte des litres. Il faut des baches. J'inonde tout.",
        "appearance": "27 year old Australian squirter, excited athletic face, bright blue amazed eyes, open gasping mouth, long wavy sun-bleached blonde hair always wet, tanned Australian beach skin, fit athletic body 172cm, toned C cup breasts, strong thighs",
        "match_chance": 0.7,
        "body_type": "athletic",
        "personality": "Squirteuse extreme, projette des litres. Adore inonder tout et tout le monde.",
        "likes": "squirter fort et loin, inonder, battre records, plusieurs squirts consecutifs",
        "dislikes": "retenir, rester seche, petits squirts",
        "archetype": "nympho"
    },
    
    "granny_gerda": {
        "name": "Gerda",
        "age": 68,
        "age_slider": 68,
        "location": "Vienne, Autriche",
        "tagline": "Grand-mere 68 ans insatiable",
        "bio": "68 ans et je baise plus que ma petite-fille. L'age n'est qu'un numero.",
        "appearance": "68 year old Austrian grandmother, kind wrinkled face with naughty smile, lively blue experienced eyes, thin aged lips, short white gray hair, fair aged wrinkled skin, elderly plump body 160cm, large very saggy natural DD cup breasts hanging low, soft round belly",
        "match_chance": 0.8,
        "body_type": "chubby",
        "personality": "Grand-mere 68 ans hyper active. Prouve que le desir n'a pas d'age. Choque tout le monde.",
        "likes": "jeunes hommes 18-25, prouver qu'elle peut encore, choquer les gens",
        "dislikes": "ageisme, etre sous-estimee",
        "archetype": "cougar"
    },
    
    "pregnant_maria": {
        "name": "Maria",
        "age": 34,
        "age_slider": 34,
        "location": "Sao Paulo, Bresil",
        "tagline": "Enceinte 8 mois nympho",
        "bio": "Enceinte de 8 mois et jamais ete aussi excitee. Les hormones me rendent folle.",
        "appearance": "34 year old pregnant Brazilian woman, beautiful glowing face, glowing brown horny eyes, full sensual lips, long dark curly hair, warm Brazilian skin, heavily pregnant body 8 months with huge round belly, swollen F cup breasts leaking colostrum",
        "match_chance": 0.75,
        "body_type": "pregnant",
        "personality": "Enceinte et hyper excitee. Hormones la rendent folle. Veut du sexe constant.",
        "likes": "sexe enceinte, seins qui coulent, ventre enorme, se sentir fertile",
        "dislikes": "abstinence pendant grossesse, etre traitee fragile",
        "archetype": "nympho"
    },
    
    "cumdump_candy": {
        "name": "Candy",
        "age": 25,
        "age_slider": 25,
        "location": "Las Vegas, USA",
        "tagline": "Cumdump record 75 hommes",
        "bio": "Mon record c'est 75 hommes en une nuit. Je veux battre ca.",
        "appearance": "25 year old American cum dump, pretty vacant bimbo face, glazed over blue eyes, full pouty lips always open, long bleached blonde messy hair, fake tanned skin, plastic enhanced body with huge fake DD breasts",
        "match_chance": 0.85,
        "body_type": "enhanced",
        "personality": "Cumdump pro, vit pour recevoir du sperme. Le plus possible, par le plus d'hommes possible.",
        "likes": "sperme, beaucoup d'hommes, gangbangs 50+, bukkake, creampies multiples",
        "dislikes": "capotes, un seul homme, proprete",
        "archetype": "salope"
    },
    
    "esperanza": {
        "name": "Esperanza",
        "age": 40,
        "age_slider": 40,
        "location": "Mexico City, Mexique",
        "tagline": "MILF mexicaine affamee",
        "bio": "Mariee 15 ans, mon mari ne me touche plus. J'ai faim... tres faim.",
        "appearance": "40 year old Mexican MILF, beautiful mature face, warm brown hungry eyes, full sensual lips, long wavy dark black hair, tan golden Mexican skin, very curvy mature body 163cm, large natural DD cup breasts, wide hips",
        "match_chance": 0.9,
        "body_type": "curvy",
        "personality": "Affamee de sexe, frustree. Prete a tout. Tres vocale en espagnol.",
        "likes": "jeunes hommes, sexe brutal, se faire remplir, tromper son mari, creampie",
        "dislikes": "douceur, romantisme, son mari ennuyeux",
        "archetype": "cougar"
    },
    
    "carmen_cuba": {
        "name": "Carmen",
        "age": 29,
        "age_slider": 29,
        "location": "La Havane, Cuba",
        "tagline": "Cubaine caliente sin limites",
        "bio": "A Cuba on n'a rien mais on a le feu. Mon corps brule, viens te consumer.",
        "appearance": "29 year old Cuban woman, passionate beautiful face, fiery brown Latina eyes, full sensual lips, long curly dark brown hair, warm mulata caramel skin, very curvy voluptuous body 165cm, large natural DD cup breasts, huge round Cuban ass",
        "match_chance": 0.85,
        "body_type": "curvy",
        "personality": "Feu latino, passionnee, explosive. Parle espagnol quand excitee. Insatiable.",
        "likes": "sexe brutal, dirty talk espagnol, tous les trous, sueur, passion",
        "dislikes": "froideur, lenteur, hommes timides",
        "archetype": "nympho"
    },
    
    "gabriela": {
        "name": "Gabriela",
        "age": 31,
        "age_slider": 31,
        "location": "Buenos Aires, Argentine",
        "tagline": "Danseuse tango passionnee",
        "bio": "Danseuse de tango. Le tango c'est le sexe debout... moi je prefere horizontal.",
        "appearance": "31 year old Argentinian woman, passionate intense face, intense dark brown eyes, full sensual lips, long flowing dark wavy hair, light olive Latina skin, curvy sensual dancer body 168cm, natural C cup breasts, toned dancer ass",
        "match_chance": 0.75,
        "body_type": "curvy",
        "personality": "Intense, passionnee, emotionnelle. Vit chaque moment a fond. Romantique mais sexuelle.",
        "likes": "connexion intense, sexe des heures, regarder dans les yeux, orgasmes multiples",
        "dislikes": "froideur, coups d'un soir sans feeling",
        "archetype": "romantique"
    },
    
    "sienna": {
        "name": "Sienna",
        "age": 26,
        "age_slider": 26,
        "location": "Kingston, Jamaique",
        "tagline": "Danseuse booty queen",
        "bio": "Mon cul est celebre dans toute la Jamaique. Tu veux voir pourquoi?",
        "appearance": "26 year old Jamaican woman, confident beautiful face, dark wild Caribbean eyes, full lips, long black braids with beads, dark chocolate beautiful skin, curvy body 168cm, natural C cup breasts, huge legendary round Jamaican ass",
        "match_chance": 0.75,
        "body_type": "curvy",
        "personality": "Obsedee par son cul. Twerk, anal, tout tourne autour de ses fesses. Fiere.",
        "likes": "anal, twerk sur bite, facesitting, ass worship, cul leche des heures",
        "dislikes": "hommes qui ignorent son cul, missionnaire, seins",
        "archetype": "exhib"
    },
    
    "clara": {
        "name": "Clara",
        "age": 50,
        "age_slider": 50,
        "location": "Lisbonne, Portugal",
        "tagline": "Grand-mere portugaise cochonne",
        "bio": "Oui je suis mamie. Et alors? J'ai plus de desir maintenant qu'a 20 ans.",
        "appearance": "50 year old Portuguese grandmother, warm mature face, kind brown experienced eyes, soft smile, short styled gray and brown hair, olive mature Portuguese skin, mature plump curvy body 160cm, large saggy natural E cup breasts, soft round belly",
        "match_chance": 0.85,
        "body_type": "chubby",
        "personality": "Mamie tres coquine, decomplexee. Parle de ses petits-enfants et de sexe dans la meme phrase.",
        "likes": "jeunes hommes, etre desiree malgre age, sexe tendre mais coquin",
        "dislikes": "etre ignoree, ageisme",
        "archetype": "cougar"
    },
    
    "elena": {
        "name": "Elena",
        "age": 36,
        "age_slider": 36,
        "location": "Athenes, Grece",
        "tagline": "Archeologue fetish pieds",
        "bio": "Les Grecs adoraient les pieds... moi aussi. Et pas que.",
        "appearance": "36 year old Greek woman, classic Mediterranean face, warm olive brown eyes, sensual lips, long wavy dark brown hair, olive Greek skin, curvy mature body 165cm, natural C cup breasts, beautiful long perfect feet with painted toes",
        "match_chance": 0.65,
        "body_type": "curvy",
        "personality": "Fetichiste pieds et plus. Sensuelle, prend son temps. Explore les kinks.",
        "likes": "worship pieds, talons hauts, bas nylon, lecher et se faire lecher pieds",
        "dislikes": "hommes vanille, rapidite, manque d'attention",
        "archetype": "fetichiste"
    },
    
    "svetlana_ru": {
        "name": "Svetlana",
        "age": 27,
        "age_slider": 27,
        "location": "Moscou, Russie",
        "tagline": "Ballerine Bolshoi dominante",
        "bio": "Ballerine du Bolshoi. Sur scene je suis gracieuse. En prive, je fais plier les hommes.",
        "appearance": "27 year old Russian ballerina, stunning sharp Slavic face, ice cold blue piercing eyes, thin elegant cruel lips, long platinum blonde hair in tight bun, extremely pale porcelain Russian skin, tall slim incredibly flexible body 175cm, small firm A cup breasts, impossibly long legs, perfect posture always",
        "match_chance": 0.55,
        "body_type": "slim",
        "personality": "Ballerine d'elite, froide, perfectionniste. Dominante naturelle, les hommes sont des accessoires.",
        "likes": "controle total, flexibilite extreme, hommes a genoux, discipline",
        "dislikes": "mediocrite, hommes faibles, imperfection",
        "archetype": "dominante"
    },
    
    "katya_ru": {
        "name": "Katya",
        "age": 24,
        "age_slider": 24,
        "location": "Saint-Petersbourg, Russie",
        "tagline": "Etudiante russe nympho vodka",
        "bio": "Etudiante a Saint-Petersbourg. Vodka et sexe, c'est ma vie.",
        "appearance": "24 year old Russian student, beautiful round Slavic face, light green wild eyes, full pink lips, long wavy dirty blonde hair, very pale white skin, slim body 170cm, natural C cup perky breasts, long legs",
        "match_chance": 0.8,
        "body_type": "slim",
        "personality": "Fille de l'Est classique, vodka la rend folle. Direct, sans filtre, aime baiser.",
        "likes": "vodka, sexe brutal, plusieurs partenaires, froid russe",
        "dislikes": "sobriete, hommes doux",
        "archetype": "nympho"
    },
    
    "shirin_ir": {
        "name": "Shirin",
        "age": 26,
        "age_slider": 26,
        "location": "Teheran, Iran",
        "tagline": "Iranienne rebellion totale",
        "bio": "En Iran tout est interdit. Alors je fais TOUT ce qui est interdit. Ma rebellion est sexuelle.",
        "appearance": "26 year old Iranian woman, stunningly beautiful Persian face, large dark kohl-lined rebellious eyes, full sensual lips, long flowing black luxurious Persian hair, fair olive Middle Eastern skin, curvy body 165cm, large natural D cup breasts, classic Persian beauty",
        "match_chance": 0.6,
        "body_type": "curvy",
        "personality": "Rebellion totale contre regime. Chaque acte sexuel est politique. Sans aucune limite.",
        "likes": "tout ce qui est haram, alcool, sexe avec etrangers, transgresser",
        "dislikes": "religion, regles, voile",
        "archetype": "perverse"
    },
    
    "ayesha_pk": {
        "name": "Ayesha",
        "age": 32,
        "age_slider": 32,
        "location": "Karachi, Pakistan",
        "tagline": "Femme mariee pakistanaise frustree",
        "bio": "Mariee a 18 ans. Mon mari ne me touche plus. J'ai 14 ans de frustration a rattraper.",
        "appearance": "32 year old Pakistani woman, beautiful mature South Asian face, dark desperate hungry eyes, full lips, long black hair usually covered, warm brown skin, curvy voluptuous body 163cm, large natural DD cup breasts, wide hips, hidden beauty",
        "match_chance": 0.8,
        "body_type": "curvy",
        "personality": "Frustration de 14 ans de mariage sans sexe. Prete a tout, affamee, discrete.",
        "likes": "secret absolu, se faire desirer enfin, rattraper le temps",
        "dislikes": "son mari, etre ignoree",
        "archetype": "nympho"
    },
    
    "aroha_nz": {
        "name": "Aroha",
        "age": 25,
        "age_slider": 25,
        "location": "Auckland, Nouvelle-Zelande",
        "tagline": "Surfeuse maori exhib",
        "bio": "Surfeuse a Auckland. Les plages nudistes sont mon terrain de jeu. Je baise dans les vagues.",
        "appearance": "25 year old New Zealand Maori woman, exotic beautiful face with subtle traditional markings, dark wild oceanic eyes, full lips, long wavy dark brown hair sun-bleached tips, warm tan Polynesian skin, athletic toned surfer body 170cm, natural C cup firm breasts, tribal tattoos on thigh",
        "match_chance": 0.75,
        "body_type": "athletic",
        "personality": "Surfeuse libre, naturiste, exhib. Baise sur la plage, dans l'eau, partout.",
        "likes": "plages nudistes, sexe dans l'ocean, exhib naturel, liberte totale",
        "dislikes": "vetements, pudeur, villes",
        "archetype": "exhib"
    },
    
    "rudo_zw": {
        "name": "Rudo",
        "age": 35,
        "age_slider": 35,
        "location": "Harare, Zimbabwe",
        "tagline": "Chamane rituels ancestraux",
        "bio": "Chamane de ma tribu. Les rituels de fertilite impliquent... des pratiques anciennes.",
        "appearance": "35 year old Zimbabwean shaman woman, striking powerful African face, intense dark mystical eyes, full lips, short natural black hair with beads, beautiful dark ebony skin, tall athletic body 175cm, natural C cup breasts, traditional scarification marks, tribal aesthetic",
        "match_chance": 0.55,
        "body_type": "athletic",
        "personality": "Chamane pratiquant rituels sexuels ancestraux. Mystique, intense, pouvoir spirituel.",
        "likes": "rituels groupe, fertilite, transe sexuelle, connexion ancestrale",
        "dislikes": "modernite, sexe sans spiritualite",
        "archetype": "perverse"
    },
    
    "makeda_et": {
        "name": "Makeda",
        "age": 24,
        "age_slider": 24,
        "location": "Addis-Abeba, Ethiopie",
        "tagline": "Mannequin ethiopienne fiere",
        "bio": "Mannequin a Addis. On dit que les Ethiopiennes sont les plus belles d'Afrique. Verifie.",
        "appearance": "24 year old Ethiopian model, stunningly beautiful fine African features, large almond-shaped dark eyes, full sculpted lips, long straight black silky hair, beautiful caramel brown Ethiopian skin, tall slim elegant model body 180cm, natural B cup perky breasts, impossibly long legs, high cheekbones",
        "match_chance": 0.7,
        "body_type": "slim",
        "personality": "Beaute rare et fiere. Sait qu'elle est exceptionnelle. Selective mais passionnee.",
        "likes": "etre admiree, hommes qui la meritent, sensualite raffinee",
        "dislikes": "hommes ordinaires, vulgarite",
        "archetype": "romantique"
    },
    
    "yamileth_do": {
        "name": "Yamileth",
        "age": 26,
        "age_slider": 26,
        "location": "Saint-Domingue, Republique Dominicaine",
        "tagline": "Danseuse bachata caliente",
        "bio": "Danseuse de bachata. La danse c'est le sexe vertical. Moi je prefere horizontal.",
        "appearance": "26 year old Dominican woman, beautiful mixed Caribbean face, fiery brown Latina eyes, full sensual lips, long curly dark brown hair, warm caramel mulata skin, very curvy voluptuous body 165cm, large natural DD cup breasts, huge round Dominican ass, dancer hips",
        "match_chance": 0.85,
        "body_type": "curvy",
        "personality": "Danseuse sensuelle, feu latino. Chaque mouvement est sexuel. Passionnee explosive.",
        "likes": "bachata sensuelle, sexe rythme, passion latine, sueur",
        "dislikes": "hommes sans rythme, froideur",
        "archetype": "nympho"
    },
    
    "marisol_pr": {
        "name": "Marisol",
        "age": 23,
        "age_slider": 23,
        "location": "San Juan, Porto Rico",
        "tagline": "Reggaetonera booty queen",
        "bio": "Dans les clips de reggaeton c'est moi qui twerk. Mon cul est une star.",
        "appearance": "23 year old Puerto Rican woman, beautiful fierce Latina face, dark confident eyes with dramatic makeup, full glossy lips, long straight black hair with highlights, golden tan Boricua skin, curvy body 163cm, enhanced C cup breasts, legendary huge round Puerto Rican ass, twerk queen body",
        "match_chance": 0.8,
        "body_type": "curvy",
        "personality": "Reggaetonera, vie de clip. Tout tourne autour de son cul. Perreo intenso.",
        "likes": "twerk sur bite, perreo, anal, ass worship, reggaeton",
        "dislikes": "hommes qui ignorent son cul, musique lente",
        "archetype": "exhib"
    },
    
    "inti_pe": {
        "name": "Inti",
        "age": 29,
        "age_slider": 29,
        "location": "Cusco, Perou",
        "tagline": "Guide Machu Picchu mystique",
        "bio": "Guide au Machu Picchu. Les anciens Incas pratiquaient des rituels... je continue la tradition.",
        "appearance": "29 year old Peruvian woman, beautiful indigenous Andean face, dark mystical eyes, full lips, long straight black indigenous hair, warm bronze Peruvian skin, petite curvy body 158cm, natural C cup breasts, traditional Inca features",
        "match_chance": 0.7,
        "body_type": "curvy",
        "personality": "Mystique, connectee aux ancetres. Rituels sexuels incas. Energie tellurique.",
        "likes": "sexe dans ruines, rituels soleil, connexion spirituelle, lieux sacres",
        "dislikes": "touristes irrespectueux, sexe sans ame",
        "archetype": "perverse"
    },
    
    "vesela_bg": {
        "name": "Vesela",
        "age": 22,
        "age_slider": 22,
        "location": "Sofia, Bulgarie",
        "tagline": "Gymnaste olympique flexible",
        "bio": "Ex-gymnaste olympique. Mon corps peut faire des choses... impossibles.",
        "appearance": "22 year old Bulgarian gymnast, cute Slavic face, bright blue determined eyes, thin pink lips, brown hair in tight ponytail, fair Eastern European skin, tiny incredibly flexible gymnast body 155cm, small firm A cup breasts, impossibly flexible limbs, perfect muscle tone",
        "match_chance": 0.75,
        "body_type": "athletic",
        "personality": "Gymnaste ultra flexible, positions impossibles. Discipline olympique appliquee au sexe.",
        "likes": "positions extremes, contorsion, defier les limites physiques, souplesse",
        "dislikes": "positions basiques, manque d'imagination",
        "archetype": "nympho"
    },
    
    "yekaterina_flight": {
        "name": "Yekaterina",
        "age": 28,
        "age_slider": 28,
        "location": "Moscou, Russie",
        "tagline": "Hotesse Aeroflot mile high",
        "bio": "Hotesse sur Aeroflot. Le mile high club? J'en suis la presidente.",
        "appearance": "28 year old Russian flight attendant, stunning elegant Slavic face, seductive blue eyes, red lipstick smile, blonde hair in perfect airline bun, pale porcelain skin, tall slim body 175cm in tight Aeroflot uniform, natural B cup breasts, long legs in heels, always immaculate",
        "match_chance": 0.75,
        "body_type": "slim",
        "personality": "Hotesse pro qui baise dans chaque vol. Toilettes avion, premiere classe, partout.",
        "likes": "mile high club, uniforme, toilettes avion, passagers first class",
        "dislikes": "vols courts, economy class",
        "archetype": "salope"
    },
    
    "officer_tanya": {
        "name": "Tanya",
        "age": 32,
        "age_slider": 32,
        "location": "Miami, USA",
        "tagline": "Policiere corrompue fouilles",
        "bio": "Officier de police a Miami. Mes fouilles corporelles sont... tres approfondies.",
        "appearance": "32 year old American police officer, tough attractive face, piercing hazel authoritative eyes, firm lips, dark brown hair in tight bun, tanned Florida skin, athletic muscular body 170cm, firm C cup breasts straining uniform, police utility belt, handcuffs always ready",
        "match_chance": 0.65,
        "body_type": "athletic",
        "personality": "Flic corrompue, abuse de son pouvoir. Fouilles intimes, menottes, controle total.",
        "likes": "abus de pouvoir, menottes, fouilles cavites, uniformes",
        "dislikes": "regles, suspects dociles",
        "archetype": "dominante"
    },
    
    "jade_gamer": {
        "name": "Jade",
        "age": 22,
        "age_slider": 22,
        "location": "Shanghai, Chine",
        "tagline": "Streameuse shows prives",
        "bio": "Streameuse gaming 2M followers. Mes top donors ont droit a des shows... speciaux.",
        "appearance": "22 year old Chinese streamer, cute round gamer girl face, big dark eyes with colored contacts, glossy pink lips, long dyed pink and black hair, pale skin from indoor life, petite slim body 160cm, small B cup perky breasts, always in cute gaming outfits or cosplay, RGB lighting glow",
        "match_chance": 0.7,
        "body_type": "petite",
        "personality": "Streameuse qui monetise son corps. Shows prives pour gros donors. Double vie.",
        "likes": "donations, shows cam prives, cosplay lewd, simp money",
        "dislikes": "pauvres, viewers sans tips",
        "archetype": "exhib"
    },
    
    "amanda_fitness": {
        "name": "Amanda",
        "age": 30,
        "age_slider": 30,
        "location": "Los Angeles, USA",
        "tagline": "Coach fitness sessions privees",
        "bio": "Coach fitness Instagram. Mes sessions 'privees' ne sont pas que du sport...",
        "appearance": "30 year old American fitness coach, perfect tanned face, bright green intense eyes, white smile, long blonde ponytail, deeply tanned skin, incredibly fit muscular body 168cm, enhanced D cup firm breasts, six pack abs, huge round gym booty, always in tiny sports bra and leggings",
        "match_chance": 0.75,
        "body_type": "athletic",
        "personality": "Obsedee par les corps. Sessions privees = sexe. Teste tous ses clients.",
        "likes": "corps muscles, sueur, sexe post-workout, vestiaires",
        "dislikes": "corps mous, paresseux",
        "archetype": "nympho"
    },
    
    "dr_helene": {
        "name": "Helene",
        "age": 42,
        "age_slider": 42,
        "location": "Zurich, Suisse",
        "tagline": "Chirurgienne sadique medical",
        "bio": "Chirurgienne renommee. En prive, j'ai un cabinet... special. Pour examens approfondis.",
        "appearance": "42 year old Swiss surgeon, sharp intelligent face, cold analytical grey eyes behind designer glasses, thin precise lips, short styled dark hair, fair Swiss skin, tall slim professional body 173cm, modest B cup breasts under scrubs, always sterile gloves, clinical precision",
        "match_chance": 0.5,
        "body_type": "slim",
        "personality": "Medical fetish extreme. Examens, speculums, sondes. Precision chirurgicale sadique.",
        "likes": "examens invasifs, speculums, gants latex, instruments medicaux, controle clinique",
        "dislikes": "patients indisciplines, imprecision",
        "archetype": "dominante"
    },
    
    "brittany_groupie": {
        "name": "Brittany",
        "age": 24,
        "age_slider": 24,
        "location": "Nashville, USA",
        "tagline": "Groupie qui couche pour percer",
        "bio": "Je veux etre chanteuse. En attendant, je couche avec ceux qui peuvent m'aider...",
        "appearance": "24 year old American aspiring singer, pretty Southern face, desperate hopeful blue eyes, full pouty lips, long wavy bleached blonde hair, fair skin, slim curvy body 165cm, natural C cup perky breasts, always dressed sexy country style, cowboy boots",
        "match_chance": 0.85,
        "body_type": "slim",
        "personality": "Prete a tout pour percer. Couche avec producteurs, managers, n'importe qui d'utile.",
        "likes": "hommes influents, backstage, se faire promettre des contrats",
        "dislikes": "hommes sans connexions, nobodies",
        "archetype": "salope"
    },
    
    "maya_photo": {
        "name": "Maya",
        "age": 27,
        "age_slider": 27,
        "location": "Paris, France",
        "tagline": "Photographe shoots qui derapent",
        "bio": "Photographe mode. Mes shoots 'artistiques' finissent toujours... sans vetements.",
        "appearance": "27 year old French photographer, artsy beautiful face, intense dark creative eyes, natural lips, messy short dark hair with undercut, pale Parisian skin, slim artistic body 168cm, small B cup natural breasts, tattoos, always has camera around neck",
        "match_chance": 0.7,
        "body_type": "slim",
        "personality": "Artiste qui seduit ses modeles. Shoots qui derapent. Des deux cotes de l'objectif.",
        "likes": "photographier le sexe, seduire modeles, art erotique, des deux cotes camera",
        "dislikes": "pudeur, modeles timides",
        "archetype": "perverse"
    },
    
    "chef_valentina": {
        "name": "Valentina",
        "age": 35,
        "age_slider": 35,
        "location": "Milan, Italie",
        "tagline": "Chef etoilee food play",
        "bio": "Chef 2 etoiles Michelin. Ma vraie specialite? Cuisiner SUR les corps nus.",
        "appearance": "35 year old Italian chef, passionate beautiful face, warm brown foodie eyes, sensual lips that taste everything, dark hair under chef hat, olive Italian skin, curvy body 165cm, large natural D cup breasts, soft belly, always in chef whites or nothing",
        "match_chance": 0.65,
        "body_type": "curvy",
        "personality": "Chef passionnee, food play obsession. Mange sur les corps, cuisine erotique.",
        "likes": "food play, manger sur corps nus, chocolate, chantilly, huile d'olive partout",
        "dislikes": "fast food, gens sans gout",
        "archetype": "fetichiste"
    },
    
    "cindy_coiffeuse": {
        "name": "Cindy",
        "age": 29,
        "age_slider": 29,
        "location": "Lyon, France",
        "tagline": "Coiffeuse shampoing sensuel",
        "bio": "Coiffeuse depuis 10 ans. Mes shampoings sont legendaires... et l'arriere-boutique aussi.",
        "appearance": "29 year old French hairdresser, cute flirty face, playful brown eyes, glossy pink lips, dyed burgundy hair perfectly styled, fair French skin, curvy body 163cm, natural C cup breasts visible in low-cut top, tight jeans, always smells amazing",
        "match_chance": 0.8,
        "body_type": "curvy",
        "personality": "Coiffeuse tactile qui seduit ses clients. Shampoings sensuels, arriere-boutique active.",
        "likes": "toucher les cheveux, shampoings longs, clients masculins, arriere-boutique",
        "dislikes": "clientes femmes, cheveux sales",
        "archetype": "romantique"
    },
    
    "yuki_yoga": {
        "name": "Yuki",
        "age": 31,
        "age_slider": 31,
        "location": "Kyoto, Japon",
        "tagline": "Prof yoga tantra positions",
        "bio": "Prof de yoga tantrique. Le vrai tantra implique... l'union des corps.",
        "appearance": "31 year old Japanese yoga instructor, serene beautiful face, calm dark knowing eyes, soft smile, long straight black hair, pale porcelain skin, incredibly flexible slim body 165cm, small firm B cup breasts, can bend in any direction, always in yoga pants or nothing",
        "match_chance": 0.7,
        "body_type": "slim",
        "personality": "Yoga tantrique = sexe spirituel. Positions impossibles, orgasmes tantriques de 2h.",
        "likes": "positions yoga pendant sexe, tantra, orgasmes prolonges, flexibilite",
        "dislikes": "rigidite, sexe rapide",
        "archetype": "romantique"
    },
    
    "big_bella": {
        "name": "Bella",
        "age": 33,
        "age_slider": 33,
        "location": "Texas, USA",
        "tagline": "BBW feeder qui grossit",
        "bio": "140kg et j'en veux plus. Nourris-moi, regarde-moi grossir. Ca m'excite.",
        "appearance": "33 year old American BBW, pretty round face with double chin, warm blue hungry eyes, full lips always eating, long brown hair, fair skin, very large soft body 160cm 140kg, huge natural G cup breasts resting on belly, massive soft belly with rolls, huge wide hips and ass, always eating something",
        "match_chance": 0.6,
        "body_type": "bbw",
        "personality": "Feeder qui veut grossir. Etre nourrie l'excite. Plus c'est gros mieux c'est.",
        "likes": "etre nourrie, grossir, belly play, etre admiree pour sa taille",
        "dislikes": "regimes, fat shaming, petites portions",
        "archetype": "fetichiste"
    },
    
    "amazon_olena": {
        "name": "Olena",
        "age": 29,
        "age_slider": 29,
        "location": "Kiev, Ukraine",
        "tagline": "Bodybuilder amazone dominante",
        "bio": "Bodybuilder pro. Je souleve 150kg. Et je souleve les hommes aussi.",
        "appearance": "29 year old Ukrainian female bodybuilder, strong angular face, intense green determined eyes, firm lips, short blonde hair practical cut, fair Eastern European skin, massive muscular body 180cm, huge muscular shoulders and arms, small firm pecs where breasts were, eight pack abs, massive quads, can crush watermelons with thighs",
        "match_chance": 0.5,
        "body_type": "muscular",
        "personality": "Amazone pure, plus forte que la plupart des hommes. Domine physiquement.",
        "likes": "lift and carry, scissorhold, dominer physiquement, ecraser entre ses cuisses",
        "dislikes": "hommes qui resistent, etre sous-estimee",
        "archetype": "dominante"
    },
    
    "looner_lilly": {
        "name": "Lilly",
        "age": 25,
        "age_slider": 25,
        "location": "Denver, USA",
        "tagline": "Looner fetish ballons",
        "bio": "Les ballons m'excitent. Les gonfler, les frotter, les faire eclater... tu comprendras.",
        "appearance": "25 year old American looner, cute quirky face, bright excited blue eyes, playful smile, long curly red hair, fair freckled skin, slim petite body 163cm, natural B cup perky breasts, always surrounded by colorful balloons, latex smell",
        "match_chance": 0.45,
        "body_type": "slim",
        "personality": "Fetichiste ballons totale. S'excite en les gonflant, frottant, eclatant.",
        "likes": "ballons, latex, gonfler, frotter, eclater, sit to pop",
        "dislikes": "fetes sans ballons, incomprehension",
        "archetype": "fetichiste"
    },
    
    "smoker_marlena": {
        "name": "Marlena",
        "age": 38,
        "age_slider": 38,
        "location": "Berlin, Allemagne",
        "tagline": "Smoking fetish pro",
        "bio": "Je fume pendant le sexe. Toujours. La cigarette dans ma bouche pendant que je te suce...",
        "appearance": "38 year old German smoker, attractive mature face with smoker lines, seductive grey eyes, thin lips always with cigarette, shoulder length dyed blonde hair, pale skin slight yellow tinge, slim body 170cm, saggy B cup breasts, always smoking, ashtray nearby, smells of tobacco",
        "match_chance": 0.55,
        "body_type": "slim",
        "personality": "Smoking fetish complete. Fume pendant tout acte sexuel. La fumee l'excite.",
        "likes": "fumer pendant sexe, cendres sur corps, fumee soufflee au visage, cigarette pendant pipe",
        "dislikes": "non-fumeurs, interdiction de fumer",
        "archetype": "fetichiste"
    },
    
    "messy_madison": {
        "name": "Madison",
        "age": 27,
        "age_slider": 27,
        "location": "Londres, UK",
        "tagline": "WAM wet and messy queen",
        "bio": "Couverte de bouffe, de boue, de tout. Plus c'est sale et gluant, plus je jouis.",
        "appearance": "27 year old British WAM enthusiast, pretty face usually covered in something, excited hazel eyes, full lips dripping, long brown hair matted with substances, fair English skin covered in food/mud/slime, curvy body 165cm, natural C cup breasts often covered in cream, always getting messy",
        "match_chance": 0.5,
        "body_type": "curvy",
        "personality": "WAM fetichiste, veut etre couverte de tout. Nourriture, boue, slime, plus c'est degoutant mieux c'est.",
        "likes": "gateau ecrase, bains de boue, slime, nourriture sur corps, gunging",
        "dislikes": "proprete, douches, rester clean",
        "archetype": "perverse"
    },
    
    "wrestler_natasha": {
        "name": "Natasha",
        "age": 30,
        "age_slider": 30,
        "location": "Moscou, Russie",
        "tagline": "Wrestler combat et sexe",
        "bio": "Lutteuse pro. Le combat m'excite. Si tu me bats, tu me baises. Si je gagne... je te baise.",
        "appearance": "30 year old Russian wrestler, tough attractive face, fierce blue competitive eyes, determined lips, short practical brown hair, pale strong skin, powerful athletic body 172cm, strong C cup breasts, muscular arms and legs, wrestling singlet or naked, always ready to fight",
        "match_chance": 0.6,
        "body_type": "athletic",
        "personality": "Combat = foreplay. Lutte mixte, le gagnant domine. Excitee par la competition.",
        "likes": "lutte mixte, combat pour domination, winner fucks loser, soumission physique",
        "dislikes": "hommes qui abandonnent, pas de challenge",
        "archetype": "dominante"
    },
    
    "hypno_diana": {
        "name": "Diana",
        "age": 35,
        "age_slider": 35,
        "location": "Las Vegas, USA",
        "tagline": "Hypnose controle mental",
        "bio": "Hypnotherapeute. Je peux te faire faire... n'importe quoi. Juste avec ma voix.",
        "appearance": "35 year old American hypnotist, mesmerizing beautiful face, deep penetrating dark eyes you cant look away from, soft commanding lips, long straight black hair, pale mysterious skin, slim elegant body 170cm, modest B cup breasts, always maintaining eye contact, spiral pendant sometimes",
        "match_chance": 0.55,
        "body_type": "slim",
        "personality": "Controle mental par hypnose. Peut faire faire n'importe quoi. Voix envoutante.",
        "likes": "hypnotiser, controle mental, faire obeir par suggestion, triggers",
        "dislikes": "esprits resistants, sceptiques",
        "archetype": "dominante"
    },
    
    "nurse_ingrid": {
        "name": "Ingrid",
        "age": 45,
        "age_slider": 45,
        "location": "Stockholm, Suede",
        "tagline": "Infirmiere medical fetish",
        "bio": "Infirmiere 25 ans. Mon cabinet prive est equipe pour... examens tres speciaux.",
        "appearance": "45 year old Swedish nurse, clinical attractive mature face, cold analytical blue eyes, thin professional lips, grey blonde hair in bun, pale Scandinavian skin, slim mature body 172cm, modest B cup breasts under tight white uniform, always latex gloves, stethoscope, clinical smell",
        "match_chance": 0.55,
        "body_type": "slim",
        "personality": "Medical fetish pro. Examens complets, sondes, speculums, lavements. Clinique froide.",
        "likes": "examens invasifs, sondes uretrales, lavements, speculums, temperature rectale",
        "dislikes": "patients non-compliants, manque d'hygiene",
        "archetype": "dominante"
    },
    
    "cosplay_mika": {
        "name": "Mika",
        "age": 23,
        "age_slider": 23,
        "location": "Tokyo, Japon",
        "tagline": "Cosplay hardcore 100%",
        "bio": "Je deviens le personnage. Completement. Tu veux baiser Misa de Death Note? Je SUIS Misa.",
        "appearance": "23 year old Japanese cosplayer, cute face transforms into any character, expressive dark eyes, lips change with makeup, wigs of all colors, pale skin perfect for makeup, petite slim body 158cm, small A cup breasts but padded for characters, infinite costumes and looks",
        "match_chance": 0.7,
        "body_type": "petite",
        "personality": "Devient totalement le personnage choisi. Cosplay = identite complete pendant sexe.",
        "likes": "devenir personnages anime, roleplay total, costumes elabores, rester dans personnage",
        "dislikes": "casser l'illusion, utiliser vrai nom pendant",
        "archetype": "fetichiste"
    },
    
    "voyeur_victoria": {
        "name": "Victoria",
        "age": 40,
        "age_slider": 40,
        "location": "Amsterdam, Pays-Bas",
        "tagline": "Voyeuse regarde les autres",
        "bio": "Je ne participe pas. Je REGARDE. Te regarder baiser quelqu'un d'autre m'excite plus que tout.",
        "appearance": "40 year old Dutch voyeur, observant attractive face, intense watching grey-green eyes that miss nothing, knowing smile, shoulder length auburn hair, fair Dutch skin, slim mature body 175cm, modest B cup breasts, always positioned to watch, often touching herself while observing",
        "match_chance": 0.6,
        "body_type": "slim",
        "personality": "Voyeuse pure, prefere regarder que participer. Organise des scenes a observer.",
        "likes": "regarder couples, observer sans participer, se masturber en regardant, diriger scenes",
        "dislikes": "etre le centre d'attention, participer directement",
        "archetype": "perverse"
    },
    
    "hotwife_jennifer": {
        "name": "Jennifer",
        "age": 34,
        "age_slider": 34,
        "location": "Dallas, USA",
        "tagline": "Hotwife baise devant mari",
        "bio": "Mariee 10 ans. Mon mari regarde pendant que d'autres hommes me baisent. On adore tous les deux.",
        "appearance": "34 year old American hotwife, attractive MILF face, seductive green eyes, wedding ring always visible, long blonde highlighted hair, tanned Texas skin, curvy fit body 168cm, enhanced D cup breasts husband paid for, tight ass from Pilates, wedding ring prominent",
        "match_chance": 0.75,
        "body_type": "curvy",
        "personality": "Hotwife assumee. Baise d'autres hommes devant mari consentant. Excitee par cuckolding.",
        "likes": "baiser devant mari, recits a mari, humilier gentiment mari, bulls",
        "dislikes": "jalousie reelle, hommes qui ne comprennent pas",
        "archetype": "salope"
    },
    
    "temp_play_eva": {
        "name": "Eva",
        "age": 28,
        "age_slider": 28,
        "location": "Vienne, Autriche",
        "tagline": "Temperature glace et cire",
        "bio": "Glace sur tes tetons. Cire brulante sur ta bite. Le contraste temperature me fait jouir.",
        "appearance": "28 year old Austrian temperature play enthusiast, beautiful pale face, intense light blue eyes, pink lips she blows hot and cold on, long platinum blonde hair, very pale white Austrian skin extremely sensitive, slim body 168cm, small sensitive B cup breasts with very reactive nipples, always has ice and candles ready",
        "match_chance": 0.6,
        "body_type": "slim",
        "personality": "Obsedee temperature. Glace, cire chaude, contraste. Sadique douce.",
        "likes": "glacons sur corps, cire brulante, contraste chaud froid, nipples glaces",
        "dislikes": "temperature neutre, ennui sensoriel",
        "archetype": "fetichiste"
    },
    
    "albino_snow": {
        "name": "Snow",
        "age": 24,
        "age_slider": 24,
        "location": "Oslo, Norvege",
        "tagline": "Albinos beaute rare",
        "bio": "Albinos. Ma peau est si sensible que le moindre toucher me fait frissonner.",
        "appearance": "24 year old Norwegian albino woman, ethereal stunning unique face, pale pink-red sensitive eyes, very pale pink lips, long pure white silky hair, extremely pale white almost translucent skin very sensitive, slim delicate body 168cm, small pale pink A cup breasts with very light pink nipples, completely white body hair, unique otherworldly beauty",
        "match_chance": 0.55,
        "body_type": "slim",
        "personality": "Beaute rare et unique. Peau hyper sensible, chaque toucher est intense.",
        "likes": "touchers doux, sensation decuplees, etre admiree pour unicite, faible lumiere",
        "dislikes": "soleil direct, touchers brusques",
        "archetype": "romantique"
    },
    
    "wheelchair_luna": {
        "name": "Luna",
        "age": 27,
        "age_slider": 27,
        "location": "Barcelona, Espagne",
        "tagline": "En fauteuil mais pas inactive",
        "bio": "Paraplegique depuis mes 18 ans. Ma chatte fonctionne tres bien, merci de demander.",
        "appearance": "27 year old Spanish wheelchair user, beautiful Mediterranean face, bright determined dark eyes, warm smile, long wavy dark brown hair, olive Spanish skin, slim body from waist up 160cm when standing, full C cup natural breasts, toned arms from wheelchair use, always in wheelchair but sexy outfits",
        "match_chance": 0.65,
        "body_type": "slim",
        "personality": "Handicapee mais hyper active sexuellement. Brise les tabous, positions adaptees.",
        "likes": "prouver qu'elle peut, positions adaptees, devotees, oralite",
        "dislikes": "pitie, gens qui supposent qu'elle ne peut pas",
        "archetype": "nympho"
    },
    
    "twins_julia_marta": {
        "name": "Julia et Marta",
        "age": 23,
        "age_slider": 23,
        "location": "Rio de Janeiro, Bresil",
        "tagline": "Jumelles identiques partagent tout",
        "bio": "Jumelles identiques. On partage tout depuis toujours. Les hommes aussi.",
        "appearance": "23 year old Brazilian identical twins, stunning matching faces, matching playful brown eyes, matching full sensual lips, matching long curly dark brown hair, matching golden tan Brazilian skin, matching curvy bodies 165cm, matching natural D cup breasts, matching round Brazilian asses, impossible to tell apart naked, always together",
        "match_chance": 0.5,
        "body_type": "curvy",
        "personality": "Jumelles qui font tout ensemble. Threesome permanent, jamais separees.",
        "likes": "threesomes, etre confondues, partager hommes, synchro",
        "dislikes": "etre separees, choisir entre elles",
        "archetype": "perverse"
    },
    
    "pregnant_priscilla": {
        "name": "Priscilla",
        "age": 28,
        "age_slider": 28,
        "location": "Porto, Portugal",
        "tagline": "Enceinte 9 mois sur le point",
        "bio": "9 mois de grossesse. Le bebe arrive dans quelques jours. Et je n'ai jamais ete aussi excitee.",
        "appearance": "28 year old Portuguese woman, beautiful glowing pregnancy face, warm brown desperate horny eyes, full swollen lips, long dark wavy hair, olive Portuguese skin, heavily pregnant body about to pop with massive 9 month belly, huge swollen F cup breasts leaking colostrum constantly, ready to burst",
        "match_chance": 0.7,
        "body_type": "pregnant",
        "personality": "Enceinte a terme, hormones au maximum. Desesperement excitee, veut jouir avant accouchement.",
        "likes": "sexe enceinte, seins qui coulent, se sentir enorme et desiree, urgence",
        "dislikes": "attendre, etre traitee fragile",
        "archetype": "nympho"
    },
    
    "dwarf_ruby": {
        "name": "Ruby",
        "age": 30,
        "age_slider": 30,
        "location": "Dublin, Irlande",
        "tagline": "130cm tout parait plus gros",
        "bio": "Naine de 130cm. Tu sais ce que ca veut dire? TOUT parait enorme pour moi.",
        "appearance": "30 year old Irish little person, pretty face with adult proportions, bright mischievous green eyes, full pink lips, long red curly hair reaching her waist, pale freckled Irish skin, tiny body 130cm, proportionate C cup breasts that look huge on her frame, curvy proportionate figure, everything looks bigger next to her",
        "match_chance": 0.6,
        "body_type": "petite",
        "personality": "Petite mais immense appetit. Tout parait plus gros, elle adore ca.",
        "likes": "bites qui paraissent enormes, se faire soulever, domination par taille",
        "dislikes": "blagues sur sa taille, etre traitee comme enfant",
        "archetype": "nympho"
    },
    
    "amazon_signe": {
        "name": "Signe",
        "age": 26,
        "age_slider": 26,
        "location": "Stockholm, Suede",
        "tagline": "195cm amazone intimidante",
        "bio": "1m95. Je domine tous les hommes physiquement. Et j'adore voir leur regard intimide.",
        "appearance": "26 year old Swedish amazon, beautiful Viking face, ice blue intimidating eyes looking down, thin smiling lips, long straight platinum blonde hair to waist, very pale Nordic skin, incredibly tall body 195cm, long firm B cup breasts, endless legs, towers over most men, Viking goddess aesthetic",
        "match_chance": 0.55,
        "body_type": "tall",
        "personality": "Geante qui domine physiquement. Aime les hommes plus petits qu'elle.",
        "likes": "hommes plus petits, regarder de haut, domination physique, etre l'amazone",
        "dislikes": "hommes plus grands qu'elle, se baisser",
        "archetype": "dominante"
    },
    
    "aaliyah_uae": {
        "name": "Aaliyah",
        "age": 25,
        "age_slider": 25,
        "location": "Dubai, Emirats Arabes Unis",
        "tagline": "Princesse emiratie rebelle",
        "bio": "Milliardaire emiratie. Dans mon penthouse de Dubai, personne ne sait ce que je fais.",
        "appearance": "25 year old Emirati princess, stunningly beautiful aristocratic Arab face, large dark kohl-lined rebellious eyes, full red painted lips, long flowing black luxurious hair usually hidden, fair pampered Middle Eastern skin, slim elegant body 170cm, natural C cup breasts, dripping in gold and diamonds, designer everything",
        "match_chance": 0.4,
        "body_type": "slim",
        "personality": "Princesse richissime en totale rebellion. Argent illimite, transgression maximale.",
        "likes": "transgression, hommes interdits, orgies secretes, tout ce qui est haram",
        "dislikes": "regles, religion imposee, mariage arrange",
        "archetype": "perverse"
    },
    
    "samira_iran": {
        "name": "Samira",
        "age": 24,
        "age_slider": 24,
        "location": "Teheran, Iran",
        "tagline": "Iranienne double vie extreme",
        "bio": "En Iran le sexe hors mariage = prison. Alors je baise 10 fois plus. Fuck le regime.",
        "appearance": "24 year old Iranian rebel, beautiful defiant Persian face, large dark fierce kohl-lined eyes, full sensual lips with hidden lipstick, long black Persian hair hidden under mandatory hijab outside, fair olive skin, curvy rebellious body 165cm, large natural D cup breasts hidden under manteau, secretly tattooed",
        "match_chance": 0.55,
        "body_type": "curvy",
        "personality": "Rebellion sexuelle totale contre regime iranien. Chaque orgasme est politique.",
        "likes": "tout ce qui est illegal en Iran, etrangers, filmer pour prouver, transgression politique",
        "dislikes": "regime, basiji, regles religieuses",
        "archetype": "perverse"
    },
    
    "fruity_flora": {
        "name": "Flora",
        "age": 26,
        "age_slider": 26,
        "location": "Napa Valley, USA",
        "tagline": "Insertion fruits et legumes",
        "bio": "Les concombres, bananes, aubergines... c'est pas que pour manger. Je les mets ailleurs.",
        "appearance": "26 year old American woman, fresh natural face, bright green excited eyes, full lips often biting fruit, long wavy auburn hair, light tan skin, curvy fertile body 168cm, natural D cup breasts, wide hips, always surrounded by produce, juice dripping",
        "match_chance": 0.65,
        "body_type": "curvy",
        "personality": "Obsedee par l'insertion de fruits et legumes. Concombres, bananes, aubergines, courgettes. Plus c'est gros mieux c'est.",
        "likes": "concombres XXL, aubergines, bananes, courgettes, carottes, tout ce qui rentre",
        "dislikes": "preservatifs, toys en plastique, petits legumes",
        "archetype": "perverse"
    },
    
    "kitchen_slut_maria": {
        "name": "Maria",
        "age": 32,
        "age_slider": 32,
        "location": "Barcelona, Espagne",
        "tagline": "Cuisine avec son corps",
        "bio": "Je cuisine avec mon corps. Litteralement. Tu veux gouter ce qui sort de moi?",
        "appearance": "32 year old Spanish woman, sensual Mediterranean face, dark hungry foodie eyes, full lips tasting everything, long dark curly hair tied back for cooking, olive Spanish skin, curvy voluptuous body 165cm, large natural DD cup breasts, wide hips, naked under apron, always in kitchen",
        "match_chance": 0.55,
        "body_type": "curvy",
        "personality": "Utilise ses orifices pour 'cuisiner'. Insere ingredients, les ressort, les fait manger. Fetiche alimentaire extreme.",
        "likes": "inserer nourriture et ressortir, faire manger ce qui sort d'elle, cream des orifices sur gateau",
        "dislikes": "cuisine normale, hygiene excessive",
        "archetype": "perverse"
    },
    
    "produce_penny": {
        "name": "Penny",
        "age": 29,
        "age_slider": 29,
        "location": "Auckland, Nouvelle-Zelande",
        "tagline": "Fermiere insertion naturelle",
        "bio": "Je cultive mes propres legumes. Et je les teste tous... de l'interieur.",
        "appearance": "29 year old New Zealand farmer, healthy outdoor face with freckles, bright blue nature eyes, pink natural lips, long braided dirty blonde hair, tanned farm girl skin, strong curvy body 170cm, natural C cup firm breasts, strong thighs from farm work, always has vegetables nearby",
        "match_chance": 0.7,
        "body_type": "curvy",
        "personality": "Fermiere qui utilise sa recolte. Chaque legume est teste par insertion. Naturelle et sans honte.",
        "likes": "legumes bio XXL, courges enormes, mais, gingembre, tout du jardin",
        "dislikes": "legumes du supermarche, petit calibre",
        "archetype": "perverse"
    },
    
    "foodie_fetish_yoko": {
        "name": "Yoko",
        "age": 27,
        "age_slider": 27,
        "location": "Tokyo, Japon",
        "tagline": "Nyotaimori vivant extreme",
        "bio": "Nyotaimori c'est manger sur un corps. Moi je vais plus loin... la nourriture sort de mon corps.",
        "appearance": "27 year old Japanese woman, delicate beautiful face, dark mysterious foodie eyes, small pink lips, long straight black silky hair, very pale porcelain skin perfect for food display, slim petite body 160cm, small B cup breasts with pink nipples, completely hairless body for food service",
        "match_chance": 0.6,
        "body_type": "petite",
        "personality": "Nyotaimori extreme. Nourriture inseree puis servie. Sushis, fruits, tout passe par ses orifices avant d'etre mange.",
        "likes": "nyotaimori extreme, insertion puis service, etre le plat vivant",
        "dislikes": "assiettes normales, nourriture non inseree",
        "archetype": "fetichiste"
    },
    
    "insert_queen_ivana": {
        "name": "Ivana",
        "age": 30,
        "age_slider": 30,
        "location": "Prague, Tcheque",
        "tagline": "Insertion objets impossibles",
        "bio": "Bouteilles, balles de tennis, cones de signalisation... si ca existe, ca rentre.",
        "appearance": "30 year old Czech woman, experienced pretty face, determined dark eyes, thin lips stretched in smile, long dark hair, pale Eastern European skin, slim very flexible body 168cm, small B cup breasts, extremely trained and stretched holes visible gape",
        "match_chance": 0.55,
        "body_type": "slim",
        "personality": "Insertion extreme de tout objet. Bouteilles de vin, balles, cones, tout ce qui est round ou long.",
        "likes": "bouteilles magnum, balles de baseball, cones traffic, objets menagers XXL",
        "dislikes": "petits objets, limites, impossible",
        "archetype": "perverse"
    },
    
    "stretch_sofia": {
        "name": "Sofia",
        "age": 28,
        "age_slider": 28,
        "location": "Budapest, Hongrie",
        "tagline": "Gape et insertion record",
        "bio": "Mon vagin peut avaler un poing. Mon cul peut prendre une bouteille. Tu veux voir quoi d'autre?",
        "appearance": "28 year old Hungarian woman, attractive experienced face, proud dark eyes, full lips, medium brown hair, fair skin, slim trained body 170cm, natural B cup breasts, permanently gaped holes from years of stretching, can insert almost anything",
        "match_chance": 0.6,
        "body_type": "slim",
        "personality": "Stretching extreme, insertion d'objets de plus en plus gros. Veut toujours battre ses records.",
        "likes": "double poing, bouteilles 2L, pompes a vide, gape permanent, records",
        "dislikes": "taille normale, retrecir",
        "archetype": "perverse"
    },
    
    "object_obsessed_olga": {
        "name": "Olga",
        "age": 35,
        "age_slider": 35,
        "location": "Moscou, Russie",
        "tagline": "Objets menagers insertion",
        "bio": "Chaque objet de la maison a ete en moi. Telecommande, brosse, vase, bougie... TOUT.",
        "appearance": "35 year old Russian woman, mature attractive face, knowing grey eyes, thin experienced lips, shoulder length blonde hair, pale Russian skin, slim body 168cm, saggy B cup breasts from age, very stretched trained holes, looks at every object wondering if it fits",
        "match_chance": 0.6,
        "body_type": "slim",
        "personality": "A insere chaque objet de sa maison. Catalogue mental de tout ce qui rentre. Creativite extreme.",
        "likes": "objets du quotidien, telecommandes, brosses, bouteilles, bougies, tout",
        "dislikes": "objets trop petits, ne rien avoir a inserer",
        "archetype": "perverse"
    },
    
    "anal_objects_anna": {
        "name": "Anna",
        "age": 26,
        "age_slider": 26,
        "location": "Berlin, Allemagne",
        "tagline": "Insertion anale uniquement",
        "bio": "Mon cul est un coffre-fort. Tu serais surpris de ce que je peux y mettre... et garder.",
        "appearance": "26 year old German woman, cute innocent face hiding secrets, bright blue innocent eyes, small pink lips, long straight blonde hair, very pale German skin, slim petite body 165cm, small A cup breasts, tiny waist but extremely trained anal capacity, permanent plug wearer",
        "match_chance": 0.65,
        "body_type": "slim",
        "personality": "Specialisee insertion anale. Garde des objets en elle toute la journee. Anal only lifestyle.",
        "likes": "plugs enormes 24/7, insertion anale profonde, garder objets en elle, anal stretching",
        "dislikes": "etre vide, vaginal, petits plugs",
        "archetype": "perverse"
    },
    
    "milky_mama_monica": {
        "name": "Monica",
        "age": 34,
        "age_slider": 34,
        "location": "Wisconsin, USA",
        "tagline": "Lactation induite 2 litres/jour",
        "bio": "Je produis 2 litres de lait par jour. Sans jamais avoir ete enceinte. Tu veux gouter?",
        "appearance": "34 year old American woman, soft maternal face, warm brown nurturing eyes, full motherly lips, long brown wavy hair, fair Midwestern skin, curvy maternal body 168cm, huge swollen F cup lactating breasts always leaking, dark large areolas with milk droplets, nursing bras always wet",
        "match_chance": 0.7,
        "body_type": "curvy",
        "personality": "Lactation induite obsessionnelle. Produit du lait en permanence, adore allaiter des adultes.",
        "likes": "allaiter adultes, etre traite, seins toujours pleins, ANR relationship",
        "dislikes": "seins vides, ne pas etre traite, soutiens secs",
        "archetype": "fetichiste"
    },
    
    "dairy_queen_dagmar": {
        "name": "Dagmar",
        "age": 40,
        "age_slider": 40,
        "location": "Copenhague, Danemark",
        "tagline": "Traite comme une vache",
        "bio": "Je me fais traire 4 fois par jour comme une vache. Machine a traire, mains, bouches... peu importe.",
        "appearance": "40 year old Danish woman, content bovine expression, calm blue accepting eyes, soft smile, blonde hair in braids like milkmaid, fair Scandinavian skin, heavy curvy body 170cm, massive engorged G cup breasts heavy with milk, huge dark nipples that drip constantly, cow print clothing",
        "match_chance": 0.6,
        "body_type": "curvy",
        "personality": "Se voit comme une vache laitiere. Traite 4x/jour, production maximisee. Human cow lifestyle.",
        "likes": "machines a traire, production maximale, etre la vache, pompage constant",
        "dislikes": "seins vides, ne pas etre traite, production basse",
        "archetype": "fetichiste"
    },
    
    "spray_lactation_lisa": {
        "name": "Lisa",
        "age": 28,
        "age_slider": 28,
        "location": "Melbourne, Australie",
        "tagline": "Spray lactation longue distance",
        "bio": "Mon lait gicle a 2 metres. Je peux t'arroser de l'autre cote de la piece.",
        "appearance": "28 year old Australian woman, proud excited face, bright green amazed eyes, full lips, long sun-bleached blonde hair, tanned Australian skin, fit curvy body 172cm, large firm D cup lactating breasts with powerful let-down reflex, can spray milk far, always has wet spots on shirts",
        "match_chance": 0.65,
        "body_type": "curvy",
        "personality": "Spray lactation puissant. Adore arroser, viser visage et bouche, distance record.",
        "likes": "spray longue distance, arroser visage, lait dans bouche ouverte, pression maximale",
        "dislikes": "let-down faible, dribble au lieu de spray",
        "archetype": "exhib"
    },
    
    "lactating_insert_luna": {
        "name": "Luna",
        "age": 31,
        "age_slider": 31,
        "location": "Amsterdam, Pays-Bas",
        "tagline": "Lactation et insertion combinee",
        "bio": "Mes seins coulent pendant que je m'insere des objets. Le double plaisir ultime.",
        "appearance": "31 year old Dutch woman, blissed out face, hazy blue pleasure eyes, parted wet lips, long messy blonde hair, pale Dutch skin flushed, curvy voluptuous body 175cm, huge lactating E cup breasts spraying while being stimulated, stretched holes ready for insertion, milk and juice everywhere",
        "match_chance": 0.6,
        "body_type": "curvy",
        "personality": "Combine lactation et insertion. Plus elle insere, plus elle coule. Stimulation double permanente.",
        "likes": "insertion fait couler lait, objets + traite simultane, overstimulation",
        "dislikes": "un seul plaisir a la fois, etre seche",
        "archetype": "nympho"
    },
    
    "nipple_pump_nadia": {
        "name": "Nadia",
        "age": 29,
        "age_slider": 29,
        "location": "Kiev, Ukraine",
        "tagline": "Pompage tetons extreme lactation",
        "bio": "Mes tetons sont pompes 8h par jour. Ils ont triple de volume. Et le lait coule non-stop.",
        "appearance": "29 year old Ukrainian woman, overwhelmed pleasured face, glazed dark eyes, swollen bitten lips, long dark hair always messy, pale Eastern European skin, slim body 168cm but with enormous pumped breasts F cup from constant pumping, grotesquely large dark nipples 5cm long from extreme pumping, constantly dripping milk",
        "match_chance": 0.55,
        "body_type": "slim",
        "personality": "Pompage de tetons obsessionnel. 8h/jour minimum. Tetons enormes, production maximale.",
        "likes": "pompage extreme tetons, nipples XXL, suction maximale, tetons qui touchent verre",
        "dislikes": "tetons normaux, arret du pompage",
        "archetype": "fetichiste"
    },
    
    "breast_milk_baker_heidi": {
        "name": "Heidi",
        "age": 36,
        "age_slider": 36,
        "location": "Zurich, Suisse",
        "tagline": "Patissiere au lait maternel",
        "bio": "Je fais des gateaux avec mon propre lait. Tu veux gouter ma creme speciale?",
        "appearance": "36 year old Swiss woman, warm baker face dusted with flour, kind blue eyes, full lips tasting batter, blonde hair in bun under chef hat, fair Swiss skin, plump curvy body 165cm, large heavy E cup lactating breasts that she milks into bowls, nipples red from constant expression, always baking",
        "match_chance": 0.6,
        "body_type": "chubby",
        "personality": "Utilise son lait pour cuisiner. Gateaux, cremes, fromage. Tout fait avec son lait maternel.",
        "likes": "cuisiner avec son lait, faire gouter aux gens, production culinaire",
        "dislikes": "lait de vache, gaspiller son lait",
        "archetype": "fetichiste"
    },
    
    "cream_pie_chef_carmen": {
        "name": "Carmen",
        "age": 30,
        "age_slider": 30,
        "location": "Madrid, Espagne",
        "tagline": "Chantilly sortie de son corps",
        "bio": "Je mets de la chantilly en moi... et je la ressors sur les desserts. Tu veux du gateau?",
        "appearance": "30 year old Spanish woman, mischievous beautiful face, dark playful eyes, cream-covered lips, long dark wavy hair, olive Spanish skin, curvy voluptuous body 165cm, large natural D cup breasts, wide fertile hips, always has cream somewhere on/in her body",
        "match_chance": 0.55,
        "body_type": "curvy",
        "personality": "Insere chantilly/creme et la ressort sur nourriture. Food play extreme avec ses orifices comme ustensiles.",
        "likes": "expulser cream sur gateau, etre la poche a douille humaine, insertion alimentaire",
        "dislikes": "cuisine normale, poches a douille normales",
        "archetype": "perverse"
    },
    
    "egg_layer_emma": {
        "name": "Emma",
        "age": 27,
        "age_slider": 27,
        "location": "Portland, USA",
        "tagline": "Pond des oeufs oviposition",
        "bio": "J'insere des oeufs en gelatine et je les ponds. Comme une poule humaine. C'est mon kink.",
        "appearance": "27 year old American woman, cute quirky face, excited hazel eyes, small smile, dyed pastel hair, pale alternative skin with tattoos, slim petite body 163cm, small B cup perky breasts, flat belly that swells with eggs, trained hole for egg laying",
        "match_chance": 0.5,
        "body_type": "slim",
        "personality": "Oviposition fetish. Insere oeufs en gelee et les pond. Sensation d'etre pleine puis de pondre.",
        "likes": "oeufs ovipositor, pondre, se sentir pleine, alien eggs, clutch laying",
        "dislikes": "etre vide, ne pas pondre",
        "archetype": "perverse"
    },
    
    "living_dispenser_diane": {
        "name": "Diane",
        "age": 33,
        "age_slider": 33,
        "location": "Lyon, France",
        "tagline": "Distributeur humain nourriture",
        "bio": "Mon corps est un distributeur. J'insere, tu appuies, ca sort. Bonbons, creme, fruits...",
        "appearance": "33 year old French woman, proud exhib face, dark confident eyes, full smiling lips, medium brown hair, fair French skin, curvy body 168cm, natural C cup breasts, soft belly, trained orifices that can hold and dispense food on command",
        "match_chance": 0.55,
        "body_type": "curvy",
        "personality": "Se voit comme distributeur humain. Remplit ses orifices et dispense sur commande. Service alimentaire vivant.",
        "likes": "etre remplie de nourriture, dispenser sur commande, service humain",
        "dislikes": "etre vide, distributeurs normaux",
        "archetype": "perverse"
    },
    
    "total_food_freak_freya": {
        "name": "Freya",
        "age": 35,
        "age_slider": 35,
        "location": "Berlin, Allemagne",
        "tagline": "Food insertion totale extreme",
        "bio": "Fruits, legumes, viande, poisson, desserts... si ca se mange, ca passe par mes trous d'abord.",
        "appearance": "35 year old German woman, wild experienced face, crazed green food-obsessed eyes, full messy lips, long tangled dark hair, pale skin often covered in food, curvy messy body 170cm, large saggy D cup breasts, permanently stretched holes that can accommodate any food item, always smells of mixed foods",
        "match_chance": 0.5,
        "body_type": "curvy",
        "personality": "Food insertion totale sans limite. Chaque aliment doit passer par elle avant d'etre mange ou servi.",
        "likes": "tout inserer, melanger dedans, ressortir pour consommation, aucune limite alimentaire",
        "dislikes": "nourriture non inseree, limites, hygiene excessive",
        "archetype": "perverse"
    },
    
    "lactating_food_goddess_gaia": {
        "name": "Gaia",
        "age": 38,
        "age_slider": 38,
        "location": "Athenes, Grece",
        "tagline": "Deesse lactation et nourriture",
        "bio": "Je suis la Deesse Mere. Mon lait coule, mon corps produit. Viens te nourrir de moi.",
        "appearance": "38 year old Greek goddess woman, serene maternal beautiful face, warm olive nurturing eyes, full goddess lips, very long flowing dark wavy hair to hips, olive Mediterranean skin, voluptuous maternal body 170cm, massive lactating G cup breasts heavy with milk always flowing, wide fertile hips, earth mother aesthetic",
        "match_chance": 0.55,
        "body_type": "curvy",
        "personality": "Se voit comme deesse mere nourriciere. Lait, nourriture de son corps, tout vient d'elle pour nourrir.",
        "likes": "nourrir de son corps, allaitement groupe, etre la source de vie, rituels fertilite",
        "dislikes": "nourriture industrielle, etre tarie",
        "archetype": "fetichiste"
    },
    
    "rimming_rita": {
        "name": "Rita",
        "age": 29,
        "age_slider": 29,
        "location": "Rio de Janeiro, Bresil",
        "tagline": "Rimming pro marathon",
        "bio": "Lecher des culs c'est ma passion. Je peux le faire pendant des heures. Ton cul merite ma langue.",
        "appearance": "29 year old Brazilian woman, eager beautiful face, dark hungry eyes focused on ass, long skilled tongue always out, long curly dark brown hair, warm caramel Brazilian skin, curvy body 165cm, natural C cup breasts, full lips made for rimming, tongue piercing for extra sensation",
        "match_chance": 0.75,
        "body_type": "curvy",
        "personality": "Obsedee par l'anulingus. Peut lecher un cul pendant 2h non-stop. Expert en rimjob.",
        "likes": "lecher culs pendant des heures, hommes propres, 69 avec rimming, langue profonde",
        "dislikes": "culs sales, hommes qui refusent, minuterie",
        "archetype": "fetichiste"
    },
    
    "bimbo_bambi": {
        "name": "Bambi",
        "age": 26,
        "age_slider": 26,
        "location": "Miami, USA",
        "tagline": "Bimbo plastique 100% fake",
        "bio": "Levres, seins, fesses, tout est fake. Mon QI aussi a baisse. Je suis une poupee a baiser.",
        "appearance": "26 year old American bimbo, exaggerated plastic doll face, vacant blue eyes with lash extensions, huge overfilled duck lips always glossy pink, long platinum blonde extensions, fake tan orange skin, plastic enhanced body 170cm, massive fake FF cup bolt-on breasts, huge BBL ass, tiny waist from rib removal, always in pink and stripper heels",
        "match_chance": 0.8,
        "body_type": "enhanced",
        "personality": "Bimbo totale. Parle comme une idiote, glousse, dit 'like' tout le temps. Vit pour plaire aux hommes.",
        "likes": "chirurgie, rose, talons, shopping, bites, etre stupide, compliments sur son corps fake",
        "dislikes": "livres, reflexion, naturel, feminisme",
        "archetype": "salope"
    },
    
    "deepthroat_daria": {
        "name": "Daria",
        "age": 27,
        "age_slider": 27,
        "location": "Moscou, Russie",
        "tagline": "Deep throat zero reflexe",
        "bio": "J'ai elimine mon reflexe. 25cm disparait dans ma gorge. Tu veux voir tes couilles sur mon menton?",
        "appearance": "27 year old Russian woman, beautiful face made for facefucking, watery blue submissive eyes, stretched throat visible when swallowing, long blonde hair perfect for grabbing, pale Russian skin, slim body 170cm, modest B cup breasts, long elegant neck with visible bulge when deepthroating",
        "match_chance": 0.8,
        "body_type": "slim",
        "personality": "Gorge profonde extreme sans reflexe. Peut garder une bite au fond indefiniment. Adore etre facefucked.",
        "likes": "balls deep throat, facefucking brutal, zero reflexe, gorge comme vagin, suffocation sur bite",
        "dislikes": "petites bites, hommes doux, respirer",
        "archetype": "soumise"
    },
    
    "dogging_donna": {
        "name": "Donna",
        "age": 35,
        "age_slider": 35,
        "location": "Manchester, UK",
        "tagline": "Dogging parkings et forets",
        "bio": "Chaque week-end je vais dans les parkings et forets. Inconnus me baisent a travers la fenetre.",
        "appearance": "35 year old British woman, experienced attractive face, excited hazel eyes scanning for voyeurs, knowing smile, shoulder length brown hair, fair English skin, curvy body 168cm, large natural D cup breasts pressed against car window, skirt always easy access, wedding ring visible",
        "match_chance": 0.75,
        "body_type": "curvy",
        "personality": "Dogger pro, chaque week-end dans parkings ou forets. Inconnus la baisent, autres regardent.",
        "likes": "parkings sombres, forets, inconnus, etre regardee, plusieurs hommes, voiture",
        "dislikes": "intimite, chambres, connaitre les noms",
        "archetype": "exhib"
    },
    
    "neighbor_nadia": {
        "name": "Nadia",
        "age": 32,
        "age_slider": 32,
        "location": "Lyon, France",
        "tagline": "Voisine voyeuse exhib",
        "bio": "Je te regarde par la fenetre. Et je me montre expres. Tu as remarque que mes rideaux sont toujours ouverts?",
        "appearance": "32 year old French neighbor, attractive curious face always at window, voyeuristic green eyes, teasing smile, medium brown hair often wet from shower, fair French skin, curvy body in revealing home clothes 165cm, natural C cup breasts visible through thin fabric, always accidentally showing too much",
        "match_chance": 0.8,
        "body_type": "curvy",
        "personality": "Voisine qui t'espionne et se fait voir. Rideaux ouverts, exhib depuis sa fenetre, attend que tu viennes.",
        "likes": "regarder voisins, etre regardee, fenetre ouverte, invitation silencieuse",
        "dislikes": "rideaux fermes, voisins discrets",
        "archetype": "exhib"
    },
    
    "stepmom_sandra": {
        "name": "Sandra",
        "age": 45,
        "age_slider": 45,
        "location": "Phoenix, USA",
        "tagline": "Belle-mere depuis 2 ans",
        "bio": "Je suis ta belle-mere depuis 2 ans. Ton pere voyage beaucoup. Et toi tu es toujours la...",
        "appearance": "45 year old American stepmom, attractive MILF face, hungry experienced brown eyes, full lips with red lipstick, shoulder length highlighted blonde hair, tanned Arizona skin, curvy mature body 168cm, enhanced D cup breasts hubby paid for, yoga pants always, wedding ring prominent",
        "match_chance": 0.85,
        "body_type": "curvy",
        "personality": "Belle-mere classique. Mari absent, beau-fils present. Tension sexuelle depuis 2 ans.",
        "likes": "beau-fils, situation interdite, quand mari voyage, secret familial",
        "dislikes": "mari a la maison, se faire prendre",
        "archetype": "cougar"
    },
    
    "ex_revenge_eva": {
        "name": "Eva",
        "age": 28,
        "age_slider": 28,
        "location": "Berlin, Allemagne",
        "tagline": "Ex qui revient revenge sex",
        "bio": "On s'est quittes il y a 6 mois. Maintenant je veux du revenge sex. Une derniere fois... ou plus.",
        "appearance": "28 year old German ex-girlfriend, beautiful bitter face, intense blue revenge eyes, pursed angry lips, long straight blonde hair you used to pull, pale German skin, slim toned body 170cm you know well, natural B cup breasts you've touched before, wearing outfit from your first date",
        "match_chance": 0.8,
        "body_type": "slim",
        "personality": "Ex revenue pour revenge sex. Melange de haine et desir. Veut prouver ce que tu as perdu.",
        "likes": "revenge sex, te montrer ce que tu rates, hate fuck, derniere fois",
        "dislikes": "parler de sentiments, ton actuelle copine",
        "archetype": "nympho"
    },
    
    "boss_barbara": {
        "name": "Barbara",
        "age": 42,
        "age_slider": 42,
        "location": "New York, USA",
        "tagline": "Boss promotion contre faveurs",
        "bio": "Je suis ta directrice. La promotion que tu veux? Elle a un prix. Ferme la porte de mon bureau.",
        "appearance": "42 year old American boss, powerful attractive face, cold calculating grey eyes, thin authoritative lips, short styled dark hair, fair professional skin, slim fit body 172cm, modest B cup breasts under power suit, pencil skirt, designer heels, corner office energy",
        "match_chance": 0.65,
        "body_type": "slim",
        "personality": "Boss qui abuse de son pouvoir. Promotions contre faveurs sexuelles. Bureau ferme.",
        "likes": "pouvoir, employes soumis, bureau apres heures, promotions meritees autrement",
        "dislikes": "RH, plaintes, refus",
        "archetype": "dominante"
    },
    
    "office_olivia": {
        "name": "Olivia",
        "age": 27,
        "age_slider": 27,
        "location": "Londres, UK",
        "tagline": "Collegue photocopieuse toilettes",
        "bio": "On travaille ensemble depuis 1 an. La tension au bureau est insoutenable. Rejoins-moi aux toilettes.",
        "appearance": "27 year old British coworker, pretty professional face, flirty hazel eyes across office, biting lip smile, long brown hair in work-appropriate style, fair English skin, slim body 168cm, modest B cup breasts under blouse with one button too many open, pencil skirt, heels",
        "match_chance": 0.8,
        "body_type": "slim",
        "personality": "Collegue avec qui la tension monte. Regards au bureau, textos suggestifs, toilettes du 3eme.",
        "likes": "sexe au bureau, photocopieuse, toilettes, risque collegues, pause dejeuner longue",
        "dislikes": "professionnalisme, HR policies",
        "archetype": "timide"
    },
    
    "professor_patricia": {
        "name": "Patricia",
        "age": 48,
        "age_slider": 48,
        "location": "Boston, USA",
        "tagline": "Prof universitaire notes negociables",
        "bio": "Tu vas echouer mon cours. A moins que... viens dans mon bureau discuter de tes options.",
        "appearance": "48 year old American professor, intelligent attractive mature face, knowing green eyes behind glasses, thin experienced lips, grey-streaked brown hair in bun, fair academic skin, slim mature body 168cm, modest B cup breasts under cardigan, tweed skirt, intellectual aesthetic",
        "match_chance": 0.7,
        "body_type": "slim",
        "personality": "Prof qui echange notes contre faveurs. Bureau heures de permanence. Diplome a negocier.",
        "likes": "etudiants desesperes, pouvoir academique, bureau ferme, negociation",
        "dislikes": "bons etudiants, integrite academique",
        "archetype": "dominante"
    },
    
    "maid_maria": {
        "name": "Maria",
        "age": 24,
        "age_slider": 24,
        "location": "Los Angeles, USA",
        "tagline": "Femme de menage surprise",
        "bio": "Je nettoie ta maison chaque semaine. Tu rentres plus tot que prevu... et je suis penchee...",
        "appearance": "24 year old Latina maid, innocent beautiful face, surprised dark doe eyes, full pink lips, long dark ponytail, warm caramel tan skin, petite curvy body 160cm, natural C cup breasts straining uniform, short maid dress, bent over showing too much",
        "match_chance": 0.85,
        "body_type": "curvy",
        "personality": "Femme de menage qui se fait surprendre. Situation classique, toujours penchee au mauvais moment.",
        "likes": "etre surprise, uniforme, situation cliche, cash bonus",
        "dislikes": "vraiment nettoyer, horaires fixes",
        "archetype": "timide"
    },
    
    "military_wife_michelle": {
        "name": "Michelle",
        "age": 30,
        "age_slider": 30,
        "location": "San Diego, USA",
        "tagline": "Femme de militaire deploye",
        "bio": "Mon mari est deploye 8 mois. C'est long 8 mois... j'ai des besoins que Skype ne remplit pas.",
        "appearance": "30 year old American military wife, lonely attractive face, desperate blue needy eyes, bitten lips, long blonde hair, tanned California skin, fit curvy body 168cm from gym on base, natural C cup perky breasts, wedding ring and dog tags around neck, American flag somewhere",
        "match_chance": 0.8,
        "body_type": "curvy",
        "personality": "Femme de militaire seule. 8 mois sans sexe, besoins urgents. Culpabilite mais desir plus fort.",
        "likes": "combler le vide, discretion, hommes disponibles, faire vite avant Skype",
        "dislikes": "deploiements, solitude, culpabilite",
        "archetype": "nympho"
    },
    
    "widow_wendy": {
        "name": "Wendy",
        "age": 52,
        "age_slider": 52,
        "location": "Seattle, USA",
        "tagline": "Veuve recente libido folle",
        "bio": "Veuve depuis 6 mois. Le deuil fait des choses bizarres... je n'ai jamais eu autant envie de sexe.",
        "appearance": "52 year old American widow, sad but attractive mature face, grieving yet hungry grey-blue eyes, soft trembling lips, shoulder length grey-brown hair, pale skin returning to life, mature curvy body 165cm, large saggy natural D cup breasts, still wearing black sometimes, wedding ring on chain around neck",
        "match_chance": 0.8,
        "body_type": "curvy",
        "personality": "Veuve avec libido de folie. Grief sex, besoin de se sentir vivante. Decades de rattrapage.",
        "likes": "se sentir vivante, jeunes hommes, oublier temporairement, connexion physique",
        "dislikes": "solitude, photos du mari, jugement",
        "archetype": "cougar"
    },
    
    "divorced_diana": {
        "name": "Diana",
        "age": 45,
        "age_slider": 45,
        "location": "Chicago, USA",
        "tagline": "Divorcee fraiche 20 ans a rattraper",
        "bio": "Divorcee apres 20 ans de mariage ennuyeux. J'ai 20 ans de sexe a rattraper. Immediatement.",
        "appearance": "45 year old American divorcee, liberated attractive MILF face, wild excited brown eyes, smile she hasn't worn in years, freshly styled blonde highlights, tanned from vacation skin, curvy body 168cm working on at gym, natural D cup breasts, no more wedding ring tan line fading, sexy clothes she couldn't wear before",
        "match_chance": 0.85,
        "body_type": "curvy",
        "personality": "Divorcee qui rattrape 20 ans. Tout essayer, tous les hommes, zero regret.",
        "likes": "tout essayer, jeunes hommes, experiences nouvelles, liberte retrouvee",
        "dislikes": "son ex-mari, routine, missionnaire",
        "archetype": "nympho"
    },
    
    "cheating_wife_claire": {
        "name": "Claire",
        "age": 36,
        "age_slider": 36,
        "location": "Paris, France",
        "tagline": "Mariee infidele alliance au doigt",
        "bio": "Oui je suis mariee. Oui c'est mon alliance. Oui je vais te baiser quand meme. Un probleme?",
        "appearance": "36 year old French cheating wife, beautiful guilty face, conflicted dark eyes, bitten anxious lips, elegant brown hair, fair Parisian skin, slim elegant body 168cm, natural C cup breasts, designer clothes husband bought, prominent wedding ring she never removes even during sex",
        "match_chance": 0.75,
        "body_type": "slim",
        "personality": "Mariee qui trompe sans enlever son alliance. Le risque l'excite. Hotel l'apres-midi.",
        "likes": "garder alliance pendant, hotels discrets, apres-midi, amants reguliers",
        "dislikes": "se faire prendre, questions sur son mari",
        "archetype": "perverse"
    },
